spring.application.name=ai-llm

spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.deepseek.chat.model=deepseek-chat
spring.ai.deepseek.chat.temperature=0.7

